<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CloudOps.Worker-0b3e9127-22bd-4104-bbca-590e0be3aece</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.100.6" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.100.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloudOps.Application\CloudOps.Application.csproj" />
    <ProjectReference Include="..\CloudOps.Domain\CloudOps.Domain.csproj" />
    <ProjectReference Include="..\CloudOps.Infrastructure\CloudOps.Infrastructure.csproj" />
  </ItemGroup>
</Project>
