<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CloudOps.Application\CloudOps.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.CloudWatch" Version="4.0.103.1" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.102" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.100.6" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.100.6" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
